backend:
  name: git-gateway
  branch: master

media_folder: public/images
public_folder: /public
site_url: https://police-abuses.netlify.app

collections:
  - label: "Videos"
    name: "videos"
    editor:
      preview: false
    files:
      - label: "Videos"
        name: "videos"
        format: "json"
        file: "/src/data/videos.json"
        fields:
          - label: List
            name: list
            summary: "{{id}} - {{text}}"
            widget: list
            label_singular: video
            fields:
              - {
                  label: Description,
                  name: text,
                  widget: string,
                  required: false,
                }
              - { label: Id, name: id, widget: number, required: false }
              - { label: City, name: city, widget: string, required: false }
              - { label: State, name: state, widget: string, required: false }
              - { label: Tweet, name: tweet, widget: string, required: false }
              - {
                  label: Youtube ID,
                  name: youtube,
                  widget: string,
                  required: false,
                }
